#!/bin/bash
#
# Initialize a Postgres data file in the default directory for the operating system.
#
# Calls postgres-data script.

set -o errexit
set -o nounset
set -o xtrace

dir=`postgres-data`
initdb --pgdata=$dir --username=postgres --pwprompt --auth=password --encoding=UTF8