#!/bin/bash
#
# Stop Postgres running on the data file in the default directory for the operating system.
#
# Calls postgres-data script.

set -o errexit
set -o nounset
dir=`postgres-data`

set -o xtrace
pg_ctl -D $dir stop -s -m fast
