#!/bin/bash
#
# Stop Postgres running on the data file in the default directory for the operating system.
#
# Calls postgres-data script.
#
# Example on macOS:
#
#     pg_ctl -D /usr/local/var/postgres stop -s -m fast
#
# If you're using macOS and brew postgresql, then you may prefer:
#
#     brew services stop postgresql
#
set -o errexit
set -o nounset

ctl=`postgres-ctl`
dir=`postgres-data`
user=`postgres-user`

set -o xtrace
sudo -u "$user" "$ctl" -D "$dir" stop -s -m fast


