#!/bin/bash
#
# Stop Postgres running on the data file in the default directory for the operating system.
#
# Calls postgres-data script.

set -o errexit
set -o nounset

ctl=`postgres-ctl`
dir=`postgres-data`
user=`postgres-user`

set -o xtrace
sudo -u "$user" "$ctl" -D "$dir" stop -s -m fast


