#!/bin/bash
#
# Postgres data file default path best-guess for the current operating system.
#
#   * Debian and Ubuntu have OSTYPE "linux-gnu": /usr/local/pgsql/data
#   * Mac OS X has OSTYPE "darwin11":  /usr/local/var/postgresql/data

set -o errexit
set -o nounset
 
case "$OSTYPE" in
  linux-gnu)
    echo "/usr/local/pgsql/data"
    ;;
  darwin11)
    echo "/usr/local/var/pgsql/data"
    ;;
esac